- name: "deploy to aws"
  hosts: all
  become: yes
  remote_user: ec2-user
  vars:
        FEEDLY_ACCESS_TOKEN: "{{ lookup('env','FEEDLY_ACCESS_TOKEN') }}"
        FEEDLY_REFRESH_TOKEN: "{{ lookup('env','FEEDLY_REFRESH_TOKEN') }}"
        TELEGRAM_BOT_TOKEN: "{{ lookup('env','TELEGRAM_BOT_TOKEN') }}"
        TELEGRAM_BOT_TOKEN2: "{{ lookup('env','TELEGRAM_BOT_TOKEN2') }}"
        FREQ: "{{ lookup('env','FREQ') }}"
        COUNT: "{{ lookup('env','COUNT') }}"

#Do tasks
  tasks:

    - name: Copy newsbot service if not exist
      template:
        src: newsbot.service
        dest: /lib/systemd/system/newsbot.service
      become: yes

    - name: Copy news service if not exist
      template:
        src: news.service
        dest: /lib/systemd/system/news.service
      become: yes

    - name: Creates bot directory
      file:
        path: /home/ec2-user/bot
        state: directory

    - name: Copy script files
      copy:
        src: ../gear_news_bot.py
        dest: /home/ec2-user/bot/gear_news_bot.py

    - name: Copy script files
      copy:
        src: ../feedly_api.py
        dest: /home/ec2-user/bot/feedly_api.py 

    - name: Copy script files
      copy:
        src: ../telegram_api.py
        dest: /home/ec2-user/bot/telegram_api.py 

    - name: Create bot file .env
      shell: >
        echo "FEEDLY_ACCESS_TOKEN=$FEEDLY_ACCESS_TOKEN">/home/ec2-user/bot/.env;echo "FEEDLY_REFRESH_TOKEN=$FEEDLY_REFRESH_TOKEN">>/home/ec2-user/bot/.env;echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN">>/home/ec2-user/bot/.env
      environment:
        FEEDLY_ACCESS_TOKEN: "{{ lookup('env','FEEDLY_ACCESS_TOKEN') }}"
        FEEDLY_REFRESH_TOKEN: "{{ lookup('env','FEEDLY_REFRESH_TOKEN') }}"
        TELEGRAM_BOT_TOKEN: "{{ lookup('env','TELEGRAM_BOT_TOKEN') }}"
    - name: Create bot file .env2
      shell: >
        echo "FEEDLY_ACCESS_TOKEN=$FEEDLY_ACCESS_TOKEN">/home/ec2-user/bot/.env2;echo "FEEDLY_REFRESH_TOKEN=$FEEDLY_REFRESH_TOKEN">>/home/ec2-user/bot/.env2;echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN2">>/home/ec2-user/bot/.env2
      environment:
        FEEDLY_ACCESS_TOKEN: "{{ lookup('env','FEEDLY_ACCESS_TOKEN') }}"
        FEEDLY_REFRESH_TOKEN: "{{ lookup('env','FEEDLY_REFRESH_TOKEN') }}"
        TELEGRAM_BOT_TOKEN2: "{{ lookup('env','TELEGRAM_BOT_TOKEN2') }}"

    - name: Start newsbot service
      systemd:
        name: newsbot
        state: restarted
        enabled: yes
        daemon-reload: yes

    - name: Start news service
      systemd:
        name: news
        state: restarted
        enabled: yes
        daemon-reload: yes