- name: "deploy to aws"
  hosts: all
  become: yes
  remote_user: ec2-user
  vars:
        DB_NAME: "{{ lookup('env','FEEDLY_ACCESS_TOKEN') }}"
        DB_USER: "{{ lookup('env','FEEDLY_REFRESH_TOKEN') }}"
        DB_USER: "{{ lookup('env','TELEGRAM_BOT_TOKEN') }}"

#Do tasks
  tasks:

    - name: Copy script files
      copy:
        src: ../gear_news_bot.py
        dest: /home/ec2-user/bot/gear_news_bot.py

    - name: Copy script files
      copy:
        src: ../feedly_api.py
        dest: /home/ec2-user/bot/telegram_api.py 

    - name: Copy script files
      copy:
        src: ../feedly_api.py
        dest: /home/ec2-user/bot/telegram_api.py 

    - name: execute install script
      script: /home/ec2-user/bot/gear-news-bot.py 
      environment:
        FEEDLY_ACCESS_TOKEN: "{{ lookup('env','FEEDLY_ACCESS_TOKEN') }}"
        FEEDLY_REFRESH_TOKEN: "{{ lookup('env','FEEDLY_REFRESH_TOKEN') }}"
        TELEGRAM_BOT_TOKEN: "{{ lookup('env','TELEGRAM_BOT_TOKEN') }}"
